# URL para Render (usaremos la Internal Database URL que sale en tu imagen)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Driver y Dialecto para PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Esto es vital para Render: fuerza la conexión segura SSL
spring.datasource.url=${SPRING_DATASOURCE_URL}?sslmode=require

spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}